apiVersion: batch/v1
kind: Job
metadata:
  name: backstage-setup-job
spec:
  template:
    metadata:
      name: backstage-setup-job
    spec:
      containers:
      - name: backstage-setup-container
        image: quay.io/opsmxpublic/opsmx-custom-binaries:kubectl-spin-cli-git-bash-jq-yq  # Use an image that has bash installed, you can change this if required
        command:
        - /bin/bash
        - /scripts/install.sh  # This will point to the script in the mounted ConfigMap
        env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: backstage-env-vars  # Secret containing ADMIN_PASSWORD
              key: ARGOCD_AUTH_TOKEN
        volumeMounts:
        - name: script-volume
          mountPath: /scripts  # Mount the script to /scripts
          subPath: backstage-setup-script  # The key in the ConfigMap
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: backstage-setup-script  # The name of the ConfigMap containing your script
