apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  BACKSTAGE_APP_CONFIG_app_baseUrl: "http://localhost:7000"
  BACKSTAGE_APP_CONFIG_app_title: "Backstage"
  BACKSTAGE_APP_CONFIG_backend_baseUrl: "http://backstage-backend:7000"
  BACKSTAGE_APP_CONFIG_backend_database_url: "postgres://backstage:vcWlfkZwbIKRMgMkntidKJumUBDfBvLf@postgres-db:5432/backstage"
  BACKSTAGE_APP_CONFIG_cors: "http://localhost:3000"  # Adjust as needed
  BACKSTAGE_APP_CONFIG_auth_google_clientId: "your-google-client-id"
  BACKSTAGE_APP_CONFIG_auth_google_clientSecret: "your-google-client-secret"

