{{- if .Values.backstage.createIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Release.Namespace }}-backstage
  name: backstage
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.backstage.host }}
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 7007
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.backstage.host }}
    secretName: backstage-prod-tls
{{- end }}
