apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backstage:rbac.authorization.k8s.io/ClusterRoleBinding:backstage/backstage-argo-worfklows
  name: backstage-argo-worfklows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-argo-worfklows
subjects:
- kind: ServiceAccount
  name: backstage