apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backstage:rbac.authorization.k8s.io/ClusterRole:backstage/read-all
  name: read-all
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'