apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backstage:rbac.authorization.k8s.io/ClusterRoleBinding:backstage/backstage-argo-worfklows
  name: {{ .Release.Name }}-argo-worfklows
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}argo-worfklows
subjects:
- kind: ServiceAccount
  name: backstage
  namespace: {{ .Release.Namespace }}
