apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: argo-workflows-templates:rbac.authorization.k8s.io/ClusterRoleBinding:argo/backstage-scaffolder-argo-workflows
  name: backstage-scaffolder-argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-namespace-access
subjects:
- kind: ServiceAccount
  name: backstage-scaffolder