apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backstage:rbac.authorization.k8s.io/ClusterRole:backstage/backstage-argo-worfklows
  name: backstage-argo-worfklows
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
