apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: argo-workflows-templates:rbac.authorization.k8s.io/ClusterRole:argo/backstage-scaffolder-argo-workflows
  name: backstage-scaffolder-argo-workflows
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - roles
  - rolebindings
  verbs:
  - '*'
