apiVersion: v1
stringData:
  k8s-config.yaml: |
    {{- tpl (.Files.Get "config/k8s-config.yaml") . | b64enc | nindent 4 }}
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: backstage:/Secret:backstage/k8s-config
  name: k8s-config
type: Opaque