apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.postgresql.username | b64enc }}
  POSTGRES_PASSWORD: {{ randAlpha 32 | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc }}
kind: Secret
metadata:
  name: postgresql-config
type: Opaque