apiVersion: v1
data:
  KC_HOSTNAME: {{ .Values.keycloak.host | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ randAlpha 32 | b64enc }}
immutable: false
kind: Secret
metadata:
  name: keycloak-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
