apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Release.Namespace }}-keycloak
  name: keycloak
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.keycloak.host }}
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /realms/master
        pathType: Prefix
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /
        pathType: Exact
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /realms
        pathType: Prefix
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /resources
        pathType: Prefix
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /admin
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.keycloak.host }}
    secretName: keycloak-tls