apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.postgresql.username }}
  POSTGRES_PASSWORD: {{ randAlpha 32 | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
immutable: false
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: keycloak:external-secrets.io/ExternalSecret:keycloak/postgresql-config
    reconcile.external-secrets.io/data-hash: 4ae26367445db6d7de2e0b8fed651892
  name: postgresql-config
  ownerReferences:
    - apiVersion: external-secrets.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ExternalSecret
      name: postgresql-config
type: Opaque