apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.postgresql.username  }}
  POSTGRES_PASSWORD: {{ randAlpha 64 }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
kind: Secret
metadata:
  name: postgresql-config
type: Opaque
