apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: keycloak:/Service:keycloak/postgresql
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: postgresql
  name: postgresql
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresql
  sessionAffinity: None
  type: ClusterIP
