apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-setup-job
spec:
  template:
    spec:
      containers:
      - name: keycloak-setup
        image: quay.io/opsmxpublic/opsmx-custom-binaries:kubectl-spin-cli-git-bash-jq-yq
        command: ["/bin/bash", "/mnt/config/install.sh"]
        args: 
          - "user1password"
          - "adminpassword"
        env:
          - name: USER1_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-user-config
                key: user1-password
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-config
                key: KEYCLOAK_ADMIN_PASSWORD
        volumeMounts:
        - name: script-volume
          mountPath: /mnt/config
          subPath: install.sh
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: keycloak-setup-script
  backoffLimit: 1
