apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-script
data:
  keycloak.sh: |
    #!/bin/bash
    set -e -o pipefail
    
    sed "s/\${USER1_PASSWORD}/$USER1_PASSWORD/" /config-payloads/user-password.json > /tmp/user-password-to-be-applied.json
    # Default token expires in one minute. May need to extend. very ugly
    KEYCLOAK_TOKEN=$(curl -sS  --fail-with-body -X POST -H "Content-Type: application/x-www-form-urlencoded" \
      --data-urlencode "username=cnoe-admin" \
      --data-urlencode "password=${ADMIN_PASSWORD}" \
      --data-urlencode "grant_type=password" \
      --data-urlencode "client_id=admin-cli" \
      keycloak:8080/realms/master/protocol/openid-connect/token | jq -e -r '.access_token')
    echo "creating cnoe realm and groups"
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/realm-payload.json \
      keycloak:8080/admin/realms
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/client-scope-groups-payload.json \
      keycloak:8080/admin/realms/cnoe/client-scopes
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/group-admin-payload.json \
      keycloak:8080/admin/realms/cnoe/groups
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/group-base-user-payload.json \
      keycloak:8080/admin/realms/cnoe/groups
    
    # Create scope mapper
    echo 'adding group claim to tokens'
    CLIENT_SCOPE_GROUPS_ID=$(curl -sS -H "Content-Type: application/json" -H "Authorization: bearer ${KEYCLOAK_TOKEN}" -X GET  keycloak:8080/admin/realms/cnoe/client-scopes | jq -e -r  '.[] | select(.name == "groups") | .id')
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/group-mapper-payload.json \
      keycloak:8080/admin/realms/cnoe/client-scopes/${CLIENT_SCOPE_GROUPS_ID}/protocol-mappers/models
    
    echo "creating test users"
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/user-user1.json \
      keycloak:8080/admin/realms/cnoe/users
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @/config-payloads/user-user2.json \
      keycloak:8080/admin/realms/cnoe/users
    
    USER1ID=$(curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" 'keycloak:8080/admin/realms/cnoe/users?lastName=one' | jq -r '.[0].id')
    USER2ID=$(curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" 'keycloak:8080/admin/realms/cnoe/users?lastName=two' | jq -r '.[0].id')
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X PUT --data @/tmp/user-password-to-be-applied.json \
      keycloak:8080/admin/realms/cnoe/users/${USER1ID}/reset-password
    
    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X PUT --data @/tmp/user-password-to-be-applied.json \
      keycloak:8080/admin/realms/cnoe/users/${USER2ID}/reset-password


    echo "creating BackStage Client"

    curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X POST --data @config-payloads/client-payload-to-be-applied.json \
      keycloak:8080/admin/realms/cnoe/clients

    CLIENT_ID=$(curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X GET keycloak:8080/admin/realms/cnoe/clients | jq -e -r  '.[] | select(.clientId == "backstage") | .id')

    export CLIENT_SECRET=$(curl -sS -H "Content-Type: application/json" \
      -H "Authorization: bearer ${KEYCLOAK_TOKEN}" \
      -X GET keycloak:8080/admin/realms/cnoe/clients/${CLIENT_ID} | jq -e -r '.secret')

    CLIENT_SCOPE_GROUPS_ID=$(curl -sS -H "Content-Type: application/json" -H "Authorization: bearer ${KEYCLOAK_TOKEN}" -X GET  keycloak:8080/admin/realms/cnoe/client-scopes | jq -e -r  '.[] | select(.name == "groups") | .id')

    curl -sS -H "Content-Type: application/json" -H "Authorization: bearer ${KEYCLOAK_TOKEN}" -X PUT  keycloak:8080/admin/realms/cnoe/clients/${CLIENT_ID}/default-client-scopes/${CLIENT_SCOPE_GROUPS_ID}