type: 'config'
clusters:
  - url: https://kubernetes.default.svc.cluster.local
    name: local
    authProvider: 'serviceAccount'
    skipTLSVerify: true
    skipMetricsLookup: true
    serviceAccountToken:
      $file: /var/run/secrets/kubernetes.io/serviceaccount/token
    caData:
      $file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
